# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x86'
    jdkSourceOption: 'PreInstalled'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo 'Hello world'
      java -version
      echo 'done.'

#- task: Maven@4
#  inputs:
#    mavenPomFile: 'pom.xml'
#    goals: 'compile'
#    options: '-Dskiptests'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    mavenVersionOption: 'Default'
#    mavenAuthenticateFeed: false
#    effectivePomSkip: false
#    sonarQubeRunAnalysis: false
